// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCC.Lib.Database;

namespace TCC.Lib.Migrations
{
    [DbContext(typeof(TccRestoreDbContext))]
    partial class TccRestoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("TCC.Lib.Database.RestoreBlockJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BackupMode");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Exception");

                    b.Property<int>("JobId");

                    b.Property<int>("RestoreDestinationId");

                    b.Property<long>("Size");

                    b.Property<DateTime>("StartTime");

                    b.Property<bool>("Success");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("RestoreDestinationId");

                    b.HasIndex("StartTime");

                    b.ToTable("RestoreBlockJobs");
                });

            modelBuilder.Entity("TCC.Lib.Database.RestoreDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullDestinationPath");

                    b.HasKey("Id");

                    b.HasIndex("FullDestinationPath")
                        .IsUnique();

                    b.ToTable("RestoreDestinations");
                });

            modelBuilder.Entity("TCC.Lib.Database.RestoreJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Duration");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("RestoreJobs");
                });

            modelBuilder.Entity("TCC.Lib.Database.RestoreBlockJob", b =>
                {
                    b.HasOne("TCC.Lib.Database.RestoreJob", "Job")
                        .WithMany("BlockJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCC.Lib.Database.RestoreDestination", "RestoreDestination")
                        .WithMany("RestoreBlockJobs")
                        .HasForeignKey("RestoreDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
