image: Visual Studio 2017

environment:
  SONAR_TOKEN:
    secure: ZRrEwbfNERZYPsHvMxFC3kHLga6OzFHJQ7MpfUcqLcNCzNI112ZCyew/1zhL2SN1
  GITHUB_ACCESS_TOKEN:
    secure: 33HkOpRzd2oV5gqorwoeU80F3KynRJwjCRIMRTESBBiJYYUW4sG+9jCGCsEyo+VS

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release
platform: Any CPU
 
install:
  - choco install dotnetcore-sdk --pre --version 3.0.100-preview7-012821
  # - ps: wget "https://raw.githubusercontent.com/rducom/ALM/master/build/ComputeVersion.ps1" -outfile "ComputeVersion.ps1"
  # - ps: . .\ComputeVersion.ps1
  # - ps: $version = Compute "TCC\TCC.csproj" $env:APPVEYOR_BUILD_NUMBER $env:APPVEYOR_REPO_TAG $env:APPVEYOR_PULL_REQUEST_NUMBER
  # - ps: Update-AppveyorBuild -Version $version.Semver
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet tool install --global GitVersion.Tool --version 5.0.0-beta5.50
  - nuget install Codecov -Version 1.3.0 -Verbosity quiet

before_build:
- dotnet gitversion /l console /output buildserver /updateAssemblyInfo
- dotnet restore TCC.sln --verbosity m
- dotnet --list-sdks
- dotnet --version
- cmd: >-
    IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
    dotnet sonarscanner begin /k:"TarCompressCrypt" /d:"sonar.host.url=https://sonarcloud.io" /o:rducom-github /d:"sonar.login=%SONAR_TOKEN%" /d:sonar.cs.opencover.reportsPaths="coverage.xml" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.coverage.exclusions="**/TCC.Tests/**/*"
    ) ELSE (
    dotnet sonarscanner begin /k:"TarCompressCrypt" /d:"sonar.host.url=https://sonarcloud.io" /o:rducom-github /d:"sonar.login=%SONAR_TOKEN%" /d:sonar.cs.opencover.reportsPaths="coverage.xml" /d:sonar.coverage.exclusions="**/TCC.Tests/**/*" /d:"sonar.pullrequest.provider=github" /d:"sonar.pullrequest.branch=%APPVEYOR_REPO_BRANCH%" /d:"sonar.pullrequest.key=%APPVEYOR_PULL_REQUEST_NUMBER%" /d:"sonar.pullrequest.github.repository=rducom/TarCompressCrypt" /d:"sonar.pullrequest.github.endpoint=https://api.github.com" /d:"sonar.github.oauth=%GITHUB_ACCESS_TOKEN%"
    )

build_script:
- dotnet build -c Debug
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover  /p:CoverletOutput=..\coverage.xml
- dotnet sonarscanner end /d:"sonar.login=%SONAR_TOKEN%"

test_script:
- Codecov.1.3.0\tools\codecov -f coverage.xml

after_test:
  - ps: dotnet pack TCC\TCC.csproj --configuration Release /p:$("VersionPrefix="+$env:GitVersion_MajorMinorPatch+";VersionSuffix="+$env:GitVersion_PreReleaseTag) /p:PackageVersion=$env:GitVersion_NuGetVersionV2 -o artifacts

artifacts:
  - path: .\TCC\artifacts\**\*.nupkg

deploy:
- provider: GitHub
  auth_token:
    secure: 33HkOpRzd2oV5gqorwoeU80F3KynRJwjCRIMRTESBBiJYYUW4sG+9jCGCsEyo+VS
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
- provider: NuGet
  name: nuget_release
  api_key:
    secure: u2VIyNJijO5CsVIcKm7oBHwLNpbvV2sZfT+/UjN2JsFUUdJK5QyTuQqbYMsOHNyU
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    deploy_public: true