// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCC.Lib.Database;

namespace TCC.Lib.Migrations
{
    [DbContext(typeof(TccBackupDbContext))]
    [Migration("20190718162334_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("TCC.Lib.Database.BackupBlockJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BackupMode");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Exception");

                    b.Property<string>("FullSourcePath");

                    b.Property<int>("JobId");

                    b.Property<long>("Size");

                    b.Property<DateTime>("StartTime");

                    b.Property<bool>("Success");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("StartTime");

                    b.HasIndex("FullSourcePath", "StartTime");

                    b.ToTable("BackupBlockJobs");
                });

            modelBuilder.Entity("TCC.Lib.Database.BackupJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Duration");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("BackupJobs");
                });

            modelBuilder.Entity("TCC.Lib.Database.BackupBlockJob", b =>
                {
                    b.HasOne("TCC.Lib.Database.BackupJob", "Job")
                        .WithMany("BlockJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
